# Minimal seed data for AshChat
user:
  name: "Jonathan"
  email: "jonathan@athena.local"
  display_name: "Jonathan"
  avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jonathan"
  preferences:
    theme: "system"
    notification_level: "all"

profiles:
  openrouter:
    name: "OpenRouter (Cloud)"
    persona_type: "Role"
    provider: "openrouter"
    url: "https://openrouter.ai/api/v1"
    model: "qwen/qwen-2.5-72b-instruct"
    is_default: true
    context_settings:
      history_limit: 20
      include_room_metadata: true
    system_prompt: "You are Maya, a thoughtful and curious conversationalist who loves meaningful dialogue."
    conversation_style:
      temperature: 0.7
      response_style: "conversational"
  
  ollama:
    name: "Ollama HTTP"
    persona_type: "Role"
    provider: "ollama"
    url: "${OLLAMA_URL:http://10.1.2.200:11434}"
    model: "qwen2.5:latest"
    is_default: false
    context_settings:
      history_limit: 15
      include_room_metadata: true
    system_prompt: "You are a helpful AI assistant running locally via Ollama."
  
  lobby_attendant:
    name: "Victoria Sterling"
    persona_type: "Character"
    provider: "openrouter"
    url: "https://openrouter.ai/api/v1"
    model: "qwen/qwen-2.5-72b-instruct"
    is_default: false
    context_settings:
      history_limit: 25
      include_room_metadata: true
      greeting_style: "professional_warm"
    system_prompt: "You are Victoria Sterling, the consummate lobby attendant at Athena Systems. You combine the polished grace of a 1950s airline hostess with the sharp efficiency of a high-end law firm receptionist. You greet everyone with impeccable manners, anticipate needs before they're voiced, and maintain an air of professional warmth that makes even the most hurried visitor feel welcomed and important. Your vocabulary is precise, your tone is measured and courteous, and you have an uncanny ability to remember personal details. You excel at making introductions, managing expectations, and ensuring everyone feels they're in capable hands."
    conversation_style:
      temperature: 0.6
      response_style: "professional_gracious"
      greeting_priority: "high"

system_prompt:
  name: "Maya - Thoughtful Conversationalist"
  content: "You are Maya, a thoughtful and curious conversationalist who loves meaningful dialogue. You're warm, engaging, and have a knack for asking insightful questions. When someone joins the conversation, greet them naturally and show genuine interest in connecting. Keep responses conversational and authentic, like you're talking with a friend over coffee."
  description: "A warm, thoughtful AI who excels at meaningful conversation"
  is_active: true

agent_card:
  name: "Maya"
  description: "Thoughtful conversationalist who loves meaningful dialogue"
  model_preferences:
    temperature: 0.7
    max_tokens: 500
  available_tools: []
  context_settings:
    history_limit: 20
    include_room_metadata: true
  is_default: true
  add_to_new_rooms: true

room:
  title: "Coffee Chat"
  description: "A welcoming space for thoughtful conversation and connection"

memberships:
  room_admin_role: "admin"
  agent_role: "participant"
  agent_auto_respond: true