version: '3.8'

services:
  claude-collector:
    build: .
    container_name: claude-collector
    ports:
      - "4001:4000"
    environment:
      - MIX_ENV=prod
      - ATHENA_ENDPOINT=http://athena-capture:8080/events
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=athena-knowledge
      - NEO4J_DATABASE=athena
    volumes:
      - ~/Library/Application Support/Claude:/app/claude_logs:ro
    networks:
      - athena-network
    restart: unless-stopped
    depends_on:
      - athena-capture
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  athena-network:
    external: true
EOF'
