{application,file_system,
             [{modules,['Elixir.FileSystem','Elixir.FileSystem.Backend',
                        'Elixir.FileSystem.Backends.FSInotify',
                        'Elixir.FileSystem.Backends.FSMac',
                        'Elixir.FileSystem.Backends.FSPoll',
                        'Elixir.FileSystem.Backends.FSWindows',
                        'Elixir.FileSystem.Worker']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A file system change watcher wrapper based on [fs](https://github.com/synrc/fs)"},
              {registered,[]},
              {vsn,"0.2.10"}]}.
