# Aider Configuration File

# Use Gemini 2.0 Flash Exp (free version)
# model: "openrouter/google/gemini-2.0-flash-exp:free"
model: "openrouter/google/gemini-2.0-flash-001"

# Auto-accept architect changes
auto-accept-architect: true

# Always say yes to confirmations for smoother experience
yes-always: true

# Display in dark mode for better readability
dark-mode: true

# Enable auto commits for version control
auto-commits: true

# Enable web interface
gui: true

