# Jekyll configuration for GitHub Pages - Public Documentation Only
title: "Athena: Distributed AI Home Automation"
description: "Open source AI-assisted home automation with conversation archaeology"

# Theme
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

# Enable relative links
relative_links:
  enabled: true
  collections: true

# Exclude internal documentation from being published
exclude:
  - journal/
  - physics-of-work/
  - collaboration/
  - architecture/DEV_PROD_*.md
  - CONVERSATION_ARCHAEOLOGY.md
  - _config.yml.internal
  - SECRET_REDACTION.md